# Site Build Settings

# jekyll-paginate configuration
# paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "EUR Data Coffee Breaks"
description:	       "Schedule and resources for the EUR Data Coffee Breaks at Erasmus University Rotterdam"
author:              "EUR Research Data Stewards"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
